### ISSUE TITLE
gitignore for sensitive data

### ISSUE THREAD

**Issue by EMCain** [marcmondhaschen/NHL_Model#2]
I can't figure out from looking at your code how exactly environment variables would be set and loaded. [Here](https://scotch.io/tutorials/understanding-laravel-environment-variables) is an example for Laravel that's worth a look, but you'll have to do some digging to figure out how to do the same outside a framework. 

However, you can implement the git parts separately without loading an env file. 

1. copy config/db.inc.php and mysql_setup.sql to config/db_COPY.inc.php and mysql_setup_COPY.sql. remove the password from the copied file. 

2. add config/db.inc.php and mysql_setup.sql to your .gitignore (and make sure it is working) 

3. change the password(s) on your system since the old password is in your git history, and place the updated password(s) in config/db.inc.php and mysql_setup.sql

4. put instructions to copy and fill in config/db_COPY.inc.php and mysql_setup_COPY.sql in your README's setup instructions 

5. make sure the _COPY files stay up to date as you change the originals 

If you end up using a .env file successfully, you can consolidate all the sensitive data into a single .env file and use the same method with ignoring .env and committing .env_COPY

**Comment by marcmondhaschen** [comment]
resolved as suggested and thank you!
